### ISSUE TITLE
x64 trampoline fail

### ISSUE THREAD

**Issue by ecx** [Zeex/subhook#15] opened 2016-08-09 20:07 UTC
Hello, it is impossible to make trampoline in x64, because of disasm: it have no needed flags(imm64, etc), and does not recognize standard x64 operands: push r12, sub rsp, 0x20 etc. Will be nice to see ready to x64 disasm here. Cheers ;)

**Comment by psychonic** [comment] 2016-08-21 14:04
I also ran into this issue with a function that has the following start:

```
48 89 5C 24 08                       mov     [rsp+arg_0], rbx
48 89 74 24 10                       mov     [rsp+arg_8], rsi
57                                   push    rdi
48 83 EC 20                          sub     rsp, 20h
8B 05 A3 46 76 00                    mov     eax, cs:dword_38B726A8
48 8B FA                             mov     rdi, rdx
8B F1                                mov     esi, ecx
48 8D 1D B6 44 76 00                 lea     rbx, unk_38B724C7
A8 01                                test    al, 1
```

Trying to understand the disassembly engine, it looked like I could maybe get away with added 0x48 to prefixes since the mov and sub otherwise use the same number of bytes, but that had explosive results.

**Comment by psychonic** [comment] 2016-08-24 22:54
It turns out that adding 0x48 as a supported prefix did work for me with the function I had above.

It turned out my further issue was #17

**Comment by Zeex** [comment] 2016-08-28 04:25
I"m working on adding support for REX prefixes in `subhook_disasm()`, hopefully this will solve the issue :pray:

**Comment by psychonic** [comment] 2016-08-28 12:40
Thanks for looking into all of these!

**Comment by Zeex** [comment] 2016-08-29 04:34
No problem! Thanks for reporting bugs!

**Comment by Zeex** [comment] 2016-08-29 04:38
@psychonic @ecx I think I nailed it with latest commits (https://github.com/Zeex/subhook/commit/c86c12aff818236c29cab72d2f568253a74944c3, https://github.com/Zeex/subhook/commit/95cd7b4419622cccc16d0730400ace00fc993172), can you check please?

**Comment by psychonic** [comment] 2016-08-29 23:41
I should have some time tomorrow to test this.

**Comment by psychonic** [comment] 2016-09-04 14:46
@Zeex Sorry, just had a chance to test this now.

I haven't tried to debug yet, but when removing my own hack-fixes and using the upstream fixes, I get a crash on Win64 when calling the trampoline inside of my hook.

**Comment by psychonic** [comment] 2016-09-04 15:21
I looked into this one a bit and am still not sure what's going wrong. Some more info is below.

Start of original function:

    48 89 5C 24 08                       mov     [rsp+arg_0], rbx
    57                                   push    rdi
    48 83 EC 20                          sub     rsp, 20h
    8B 05 38 46 76 00                    mov     eax, cs:dword_38B726A8
    8B F9                                mov     edi, ecx
    48 8D 1D 4E 44 76 00                 lea     rbx, unk_38B724C7
    A8 01                                test    al, 1
    75 0B                                jnz     short loc_3840E088
    83 C8 01                             or      eax, 1
    89 05 22 46 76 00                    mov     cs:dword_38B726A8, eax
    EB 09                                jmp     short loc_3840E091

Bytes at trampoline address (0x000001ECC17208C0)

    ; Original function
    48 89 5C 24 08
    57
    48 83 EC 20
    8B 05 28 C2 5E BF
    ; Jump to original, past hook
    68 40 4B 5A 80
    C7 44 24 04 00 00 00 00
    C3

Original function is at 0x00000000805A4B30 and the jump in the trampoline goes 16 bytes past the start of the original to bypass the jump installed there, the same amount of original bytes at the start of the trampoline.

Bytes at original function address

    ; Jump to hook callback
    68 10 67 3C 80
    C7 44 24 04 01 00 00 00
    C3
    ; Leftover bytes from original, already in trampoline
    76 00

    ; Original function continued, where trampoline is jumping to
    8B F9
    48 8D 1D CE 7D 76 00
    A8 01
    75 0B

> Exception thrown at 0x000001ECC17208CA : 0xC0000005: Access violation reading location 0x000001EC80D0CAF8.

The exception is thrown at 10 bytes into the trampoline, which is in part of the original function bytes.

**Comment by psychonic** [comment] 2016-09-04 15:59
The issue is due to the trampoline being more than MAX_INT away from the original function in this case. Only a 32-bit offset is used in the original instruction with the RIP-relative addressing, and that is what is being calculated and replaced as 32-bit unconditionally.

**Comment by Zeex** [comment] 2016-09-04 16:43
So it's happening here:

```
mov     eax, cs:dword_38B726A8
```

because `cs:12345` means `RIP+12345`, and the distance becomes too big when code is copied to the trampoline, correct?

**Comment by psychonic** [comment] 2016-09-04 16:59
Yes, that's correct.

**Comment by LiquidProcessor** [comment] 2017-03-17 02:27
Any progress on this? Thanks!

**Comment by ecx** [comment] 2017-03-17 17:52
@LiquidProcessor of course! Just check the disasm struct "opcode_info opcodes" and you will be sure that problem still exist till today. There are no x64 opcodes, as I telled in first post.

**Comment by Na2CO3ren** [comment] 2018-05-14 07:58
Any progress on this problem? Thanks~~~

**Comment by jdbool** [comment] 2019-11-14 00:36
Any progress?

**Comment by Zeex** [comment] 2020-11-01 21:26
I think this bug is fixed now. Trampoline code should be allocated within 32-bit address space of the process.

**Closed by Zeex** 2020-11-01 21:26 UTC
